### ISSUE TITLE
Better program name (zpaq 7.xx or fpaq 1.xx)

### ISSUE THREAD

**Issue by pdr76** [fcorbelli/zpaqfranz#10]
Hello, excellent improvement to the already good zpaq 7.15, the name "zpaqfranz" seems very long, why didn't you just keep calling it zpaq v7.xx or fpaq or something like that.

**Comment by fcorbelli** [comment]
In fact it was (once) called zpaq 7.15-franzX, to emphasize that it was actually nothing more than an evolution of zpaq.   
I could have called it (joking) **zpaq+** (zpaq++ seems way exaggerated), or **zpaqx**, or **zpaqf**, but in 99% of cases I run from a script or use zp+TAB, so it's not a big deal  
In short, it seems right to me **not** to "take ownership" as "my" program, but just some refinements to zpaq. The author, after all, is mr. Mahoney, and I think it is fair that the main credits goes to him.  
For the same reason it does not seem right to call it "zpaq vX", because it is NOT Mahoney's code either.  
I could be wrong, it's just my opinion  

I particularly appreciate any comments or suggestion on the software, positive or even negative.

**Comment by pdr76** [comment]
But please shorten the name. There is 7zip, Zip, Rar, bzip, gzip, arj,
lzma, xz and many others, and is it zpaqfranz?
You could include PAQ (for obvious reasons) and some prefix like D for
Duplicate, A for advanced, F for Franz, B for Backup, or as you said Zpaq +
or even ZBAQ making pun between Zpaq and Bak.

**Comment by forgottenbutnotgone** [comment]
Hello pdr76, can't you just rename the execulable to whatever you want? I don't see what the issue is.

**Comment by pdr76** [comment]
Yes, I realized that franz is for Franco, I still think that fpaq or zpaq2
could be a better name. Also thank you very much.
