### ISSUE TITLE
Illegal instruction error on aarch64 while decompressing with JIT

### ISSUE THREAD

**Issue by Semisol** [fcorbelli/zpaqfranz#116]
While trying to decompress an archive from an x64 system on an aarch64 system with JIT enabled, the program crashes with `Illegal instruction`.

If I use `-DNOJIT`, it works fine.

**Comment by fcorbelli** [comment]
Can you please try the attached pre-release?
Run the b (benchmark) command and look at the output
```
zpaqfranz b
```

with and without -DNOJIT

BTW there is an autotest command

```
zpaqfranz autotest -all -to /tmp/testme
```
then run the .sh inside /tmp/testme
(about 15GB of free space is needed)

**Comment by fcorbelli** [comment]
> I can't see the attached file.

[60_4c.zip](https://github.com/user-attachments/files/16216216/60_4c.zip)
Please try

**Comment by fcorbelli** [comment]
>I am not sure this is Intel/AMD CPU (virtual? arm?)
WARNING: non Intel/AMD CPUs should be compiled with -DNOJIT

So it worked!

It is not possible to determine exactly what type of CPU is running the code: for example, under Proxmox a generic entry appears that does not report the "real" physical CPU
Therefore, I cannot do much more than WARNING, otherwise there is a risk of false positives
