### ISSUE TITLE
Would it be interesting to support zstd?

### ISSUE THREAD

**Issue by diegoabadan** [fcorbelli/zpaqfranz#12]
I saw a fast algorithm with good compression:
https://github.com/facebook/zstd

I don't know if it would bring improvements in relation to the one used by zpaq, nor how complicated it would be to include support for it, but I leave it here as a suggestion for analysis. :)

**Comment by fcorbelli** [comment]
Thank you
Embedding new compressors is not an easy task, because zpaq use its own virtual machine (yes!) to describe the algorithms used

I am currently developing an advanced chunked-extraction mechanism to allow 100% verification with free space less than the overall size of the archive. The first objective is safety, then efficiency

**Comment by diegoabadan** [comment]
Thanks for the feedback.

> The first objective is safety, then efficiency

I'm happy with this choice :)
