### ISSUE TITLE
Incomplete Transactions using space

### ISSUE THREAD

**Issue by JaitinPrakash** [fcorbelli/zpaqfranz#16]
If I start adding new files, but something goes wrong and it can't write, and results in an incomplete transaction, there is no way to remove the incomplete files and reclaim storage other than overwriting the incomplete data with new data. It would be very useful to add a "trim" command that purges incomplete transactions.

**Comment by fcorbelli** [comment]
I really like your observation
So I will implement a special trim function, and I will put it below, in pre-release version, so you can evaluate it
In the meantime, thanks for the suggestion

**Comment by fcorbelli** [comment]
[15a.zip](https://github.com/fcorbelli/zpaqfranz/files/8701191/15a.zip)
This temporary release introduce the 
### trim command

Two kind:  
_in place   zpaqfranz trim z:\2.zpaq -kill_

on other file (better)
_zpaqfranz trim z:\1.zpaq -to d:\thetrimmed.zpaq_

It's not very refined, specifically it makes a copy instead of a copy-and-trim, but that's just to see if that's what you wanted  
Thanks for the feedback

**Comment by JaitinPrakash** [comment]
This worked extremely well, and with -kill turned on completed trimming any size of incomplete transactions I made in moments. This is precisely what I was looking, and I am very thankful, as this will save countless hours and many gigabytes.

**Comment by fcorbelli** [comment]
https://github.com/fcorbelli/zpaqfranz/releases/tag/54.15
