### ISSUE TITLE
Can you use zpaqfranz to fully backup windows 10?

### ISSUE THREAD

**Issue by g-k-m** [fcorbelli/zpaqfranz#33]
Hello, i found this project while browsing online, it seems to be advertised as superior to other similar tools, however, can it be used to FULLY backup a windows 10 system? In the same way that programs like Acronis True Image and Macrium Reflect do? And when i restore from the backup, will everything be 1:1 ?

**Comment by fcorbelli** [comment]
Short version: no
It is NOT a backup software like Acronis.
It is more like a 7z or RAR or WinZIP or whatever "on steroids".
You cannot do a "full backup" of Windows 10 with 7z, neither with zpaqfranz  
(_It is very hard, almost impossible, to restore a Windows system file-by-file_)

  
You can use the specific commands (g/q) to make a copy of DATA on drive C: (aka: everything into users and whatever folder)   


By default  the c:\windows, and even programs with the -frugal switch, are excluded.  
Therefore you have to do a "manual restore"  
Why do not use Acronis or whatever?   
Because the .zpaq archive contains versioned copies (like snapshots), which Acronis-style programs are unable to do 
The space occupied is minimal and the copy time is modest.   

In "real life" scenario I use TWO software  
- a full-image backup software (once a week for example)
- zpaqfranz -frugal at every boot   

I'm doing some tests for a sector copy but, I have to tell the truth, it's a long and complex job and I don't think I will complete it

Suggestion:  try something like that (in the example writing on d:\backup of course)
```
zpaqfranz g d:\backup\franco_c.zpaq -frugal -key mygoodpassword
```

Work as always and tomorrow run the same exact command
```
zpaqfranz g d:\backup\franco_c.zpaq -frugal -key mygoodpassword
```

You'll see :)

If you have any suggestions or comments, they are always welcome

**Comment by fcorbelli** [comment]
Update  
Yes, you can, but you cannot restore :)

New 56.2 (currently pre-release) can image a full C: windows to a dd (raw) image  
Restore can be done via... 7z (!) after extracting the image, or FTK/Osf mount or whatever (to mount the backup)  
Work in progress...

**Comment by fcorbelli** [comment]
[56_2f.zip](https://github.com/fcorbelli/zpaqfranz/files/10124365/56_2f.zip)
This pre-release can do a full C: image (sector-by-sector) with something like
```
zpaqfranz a k:\thebackup.zpaq c: -image -buffer 1MB
```
(-buffer 1MB using fast NVMes, the default is 4KB, usually enough for spinning drives)

The image, once taken, must be extracted before mounted (ex OSFmount) or opened (ex. 7zip)

No VSS (yet), no restore (yet)
