### ISSUE TITLE
man/zpaqfranz.pod lists GPL3+

### ISSUE THREAD

**Issue by ppisar** [fcorbelli/zpaqfranz#70]
In:

~~~~
commit b1b7268d1c7e7f64d965dd0dcb93c4f04b31c009
Author: Franco Corbelli <77727889+fcorbelli@users.noreply.github.com>
Date:   Fri Aug 25 11:57:43 2023 +0200

    Add files via upload
~~~~

you removed Rufus license notice about GPL from zpaqfranz.cpp. However, man/zpaqfranz.pod still lists it:

~~~~
I<GPL3+> Rufus: The Reliable USB Formatting Utility.
~~~~

These so not match now.

**Comment by fcorbelli** [comment]
**You're right**, I didn't align the manual with the source, in which I mentioned the Walton license (public domain), instead of the Rufus one (GPL3)

It should now be OK.
Please note that I changed the source (zpaqfranz.cpp) slightly, for a fix on PowerPC Mac. The current one is 58.10g [the only one in the repository)

**Comment by ppisar** [comment]
Thanks.
